# Change these first
owner: pejotes # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Fotoamigo
    url: https://www.fotoamigo.pl
  - name: Beyond.pl
    url: http://www.beyond.pl
  - name: cleura.cloud
    url: https://cleura.cloud
  - name: OBJ BUF1 
    url: https://swift-buf1.citycloud.com:8080/
  - name: OBJ KNA1
    url: https://swift-kna1.citycloud.com:8080/
  - name: OBJ FRA1
    url: https://swift-fra1.citycloud.com:8080/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: maczo.pl
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** status page powered by Github"
  introMessage: Simple status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
